name: Deploy

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.12.1

      - name: Install dependencies
        run: npm install

      - name: Build for production
        run: npm run build-prod

      - name: Set up deployment
        env:
          API_KEY: ${{ secrets.API_KEY }} # Define the secret in GitHub
        run: |
          echo "API_KEY=${API_KEY}" >> .env
          npm run deploy # This will run 'gh-pages -d dist', change if needed
